particle_filter:
  ros__parameters:
    # topic names
    scan_topic: '/scan'
    odometry_topic: '/odom'
    # range data downsampling
    angle_step: 18
    max_particles: 4000
    squash_factor: 6.2
    # visualization
    viz: 1
    max_viz_particles: 60
    # ray marching method
    range_method: 'rm'
    theta_discretization: 112
    # range data filtering
    max_range: 3
    fine_timing: 0
    publish_odom: 1
    # sensor model constants
    z_short: 0.
    z_max: 0.
    z_rand: 0.
    z_hit: 1.0
    sigma_hit: 4.0
    # motion model dispersion constants
    motion_dispersion_x: 0.5
    motion_dispersion_y: 0.5
    motion_dispersion_theta: 0.5
    # sensor model variant, variant 2 good for rmgpu, 3 doesn't work for rmgpu
    rangelib_variant: 2

map_server:
  ros__parameters:
    # assuming map file is in particle_filter/maps
    map: 'hallway_0422_1'
